#jdbc properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.hibernate.ddl-auto=update


# Configure custom path for swagger
# default and redirects to ---> /swagger-ui/index.html
springdoc.swagger-ui.path=/my-ui.html

# configure custom path for api doc
# default --> http://localhost:8080/v3/api-docs
springdoc.api-docs.path=/my-api-docs

# api docs
# http://localhost:8080/v3/api-docs ===> this shows json format docs
# http://localhost:8080/v3/api-docs.yaml ==> this download yaml file