#actuators
#management.endpoints.web.exposure.include=health,info

#use wildcard '*' to expose all endpoints
management.endpoints.web.exposure.include=*

management.info.env.enabled=true

info.app.name=My Super App
info.app.description= A crazy demo app!!
info.app.version=1.0.0

#Spring Security
spring.security.user.name=saurabh
spring.security.user.password=topsecret

#Exclude individual endpoints
#management.endpoints.web.exposure.exclude=health,info


# Define custom properties
coach.name=Saurabh
team.name=ASP

#change server port
server.port=7070

#set the context Path of application
#server.servlet.context-path=/myapp